server:
  port: 8081
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/flowers_images?useSSL = false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
